In [5]:
import random
import numpy as np

In [42]:
class Hopfield:
    
    def __init__(self, num_neurons):
        self.num_neurons = num_neurons 
        self.weights = np.zeros((num_neurons, num_neurons))
        self.iter = 0
        
    def feed_forward(self, inputs):
        for i in range(0, self.num_neurons):
            for j in range(0, self.num_neurons):
                if not i == j:
                    self.weights[i][j] += inputs[i] * inputs[j]
#         self.weights = inputs.dot(inputs)
    
    def activate(self, num):
        if num > 0:
            return 1
        return -1
    
    def train(self, inputs):
        for i in inputs:
            self.feed_forward(i)
        
    def predict(self, inputs):
        result = inputs
        while (self.iter < 20000):
            for i in range(0, self.num_neurons):
                for j in range(0, self.num_neurons):
                    if not result[i] == self.weights[i][j]:
                        continue
            
            sum = 0
            r = random.choice(range(self.num_neurons))
            for i in range(0, self.num_neurons):
                sum += self.weights[i][r] * result[i]
            result[r] = self.activate(sum)
            
            self.iter += 1
        return result

In [ ]:
reference1 = np.array([[0,1,1,1,1,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0]])
reference2 = np.array([[1,1,1,1,1,1,1],
                      [0,0,0,1,0,0,0],
                      [0,0,0,1,0,0,0],
                      [0,0,0,1,0,0,0],
                      [0,0,0,1,0,0,0],
                      [0,0,0,1,0,0,0],
                      [0,0,0,1,0,0,0]])
reference3 = np.array([[1,0,0,0,0,0,1],
                      [1,0,0,0,1,1,0],
                      [1,0,0,1,0,0,0],
                      [1,1,1,0,0,0,0],
                      [1,0,0,1,0,0,0],
                      [1,0,0,0,1,1,0],
                      [1,0,0,0,0,0,1]])

references = np.array([reference1, reference2, reference3])

net_hopfield = Hopfield(7)
net_hopfield.train(references)

spoiled_reference = np.array([[1,1,0,0,0,0,0],
                      [1,0,0,0,1,1,0],
                      [1,0,0,1,0,0,0],
                      [0,0,1,0,0,0,0],
                      [1,0,0,1,0,0,0],
                      [1,0,0,0,1,1,0],
                      [1,1,0,0,0,0,1]])

#predict = net_hopfield.predict(spoiled_reference)
net_hopfield.predict(spoiled_reference)

print("Потребовалось {} итераций.".format(net_hopfield.iter))
print(spoiled_reference, end='')

In [43]:
reference1 = np.array([-1,1,-1,1])
reference2 = np.array([1,-1,1,1])
reference3 = np.array([-1,1,-1,-1])

references = np.array([reference1, reference2, reference3])

net_hopfield = Hopfield(4)
net_hopfield.train(references)

spoiled_reference = np.array([1,-1,1,-1])

#predict = net_hopfield.predict(spoiled_reference)
net_hopfield.predict(spoiled_reference)

print("Потребовалось {} итераций.".format(net_hopfield.iter))
print(spoiled_reference, end='')

Потребовалось 20000 итераций.
[ 1 -1  1  1]

In [39]:
net_hopfield.weights

array([[ 0., -3.,  3.,  1.],
       [-3.,  0., -3., -1.],
       [ 3., -3.,  0.,  1.],
       [ 1., -1.,  1.,  0.]])

In [32]:
reference1 = np.array([[0,1,1,1,1,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0]])
reference2 = np.array([[0,1,1,1,1,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0]])
reference3 = np.array([[0,1,1,1,1,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0]])

references = np.array([reference1, reference2, reference3])
for reference in references:
    print(reference)

[[0 1 1 1 1 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]]
[[0 1 1 1 1 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]]
[[0 1 1 1 1 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]]


In [29]:
# reference1 = np.array([0,1,1,1,1,1,0,
#                       0,1,0,0,0,1,0,
#                       0,1,0,0,0,1,0,
#                       0,1,0,0,0,1,0,
#                       0,1,0,0,0,1,0,
#                       0,1,0,0,0,1,0,
#                       0,1,0,0,0,1,0])
# reference2 = np.array([1,1,1,1,1,1,1,
#                       0,0,0,1,0,0,0,
#                       0,0,0,1,0,0,0,
#                       0,0,0,1,0,0,0,
#                       0,0,0,1,0,0,0,
#                       0,0,0,1,0,0,0,
#                       0,0,0,1,0,0,0])
# reference3 = np.array([1,0,0,0,0,0,1,
#                       1,0,0,0,1,1,0,
#                       1,0,0,1,0,0,0,
#                       1,1,1,0,0,0,0,
#                       1,0,0,1,0,0,0,
#                       1,0,0,0,1,1,0,
#                       1,0,0,0,0,0,1])

reference1 = np.array([[0,1,1,1,1,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0],
                      [0,1,0,0,0,1,0]])
reference2 = np.array([[1,1,1,1,1,1,1],
                      [0,0,0,1,0,0,0],
                      [0,0,0,1,0,0,0],
                      [0,0,0,1,0,0,0],
                      [0,0,0,1,0,0,0],
                      [0,0,0,1,0,0,0],
                      [0,0,0,1,0,0,0]])
reference3 = np.array([[1,0,0,0,0,0,1],
                      [1,0,0,0,1,1,0],
                      [1,0,0,1,0,0,0],
                      [1,1,1,0,0,0,0],
                      [1,0,0,1,0,0,0],
                      [1,0,0,0,1,1,0],
                      [1,0,0,0,0,0,1]])

references = np.array([reference1, reference2, reference3])

net_hopfield = Hopfield(7)
net_hopfield.train(references)

In [31]:
net_hopfield.weights

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [ ]:
spoiled_reference2 = [
        1,1,0,0,0,0,0,
        1,0,0,0,1,1,0,
        1,0,0,1,0,0,0,
        0,0,1,0,0,0,0,
        1,0,0,1,0,0,0,
        1,0,0,0,1,1,0,
        1,1,0,0,0,0,1
    ]
print(spoiled_reference2, end='')